# Generated by Django 3.2.8 on 2021-10-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('pk_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dpi', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('pk_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=9)),
                ('nombre_equipo', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('imagen1', models.URLField(default='https://i.postimg.cc/Y0gkNhTM/3aabe0e9a520b9ad90407a82f85adb42.jpg', max_length=800)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre_equipo'],
            },
        ),
    ]
