# Generated by Django 3.2.8 on 2021-10-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='codigo',
            new_name='codigo_equipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='descripcion',
            new_name='descripcion_equipo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='precio',
            new_name='precio_equipo',
        ),
    ]
